
default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: true
  pool: 5
  username: fab
  password: fab2011!
  host: localhost

development:
  <<: *default
  database: the_revelery_db_development

